# Generated by Django 3.2.9 on 2021-11-09 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'sistemapedidos_marca',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=None)),
                ('estado', models.CharField(choices=[('A', 'ABIERTO'), ('E', 'ENTREGADO'), ('P', 'PENDIENTE'), ('V', 'EN VIAJE')], default='A', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sistemapedidos_pedido',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('precio', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='img')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemapedidos.marca')),
            ],
            options={
                'db_table': 'sistemapedidos_producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemapedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemapedidos.producto')),
            ],
            options={
                'db_table': 'sistemapedidos_productopedido',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='productosPedidos',
            field=models.ManyToManyField(through='sistemapedidos.ProductoPedido', to='sistemapedidos.Producto'),
        ),
    ]
